apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.15.1
    releaseName: cert-manager
    namespace: cert-manager
    includeCRDs: false
    valuesFile: k3d-values.yaml
resources:
  - namespace.yaml
  - self-signed-root-issuer.yaml